---
settings:
  name: Google Cloud Storage
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: zh-cn,us-en,ja-jp,ko-kr,zh-tw,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: Google Cloud Storage文档
    url: "/index.html"
  - title: 发行说明
    url: "/whats-new.html"
  - title: 入门
    entries:
    - title: 查看Google Cloud存储分段
      url: "/task-viewing-gcp-storage.html"
  - title: 管理Google云存储分段
    entries:
    - title: 添加新存储分段
      url: "/task-add-gcp-bucket.html"
    - title: 更改存储分段设置
      url: "/task-change-gcp-bucket-settings.html"
    - title: 将NetApp数据服务与Google云存储分段结合使用
      url: "/task-gcp-enable-data-services.html"
  - title: 知识和支持
    entries:
    - title: 注册以获得支持
      url: "/task-support-registration.html"
    - title: 获取帮助
      url: "/task-get-help.html"
  - title: 法律声明
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: 入门
    links:
    - title: 查看Google Cloud存储分段
      url: task-viewing-gcp-storage.html
  - title: 管理Google云存储分段
    links:
    - title: 添加存储分段
      url: task-add-gcp-bucket.html
    - title: 更改存储分段设置
      url: task-change-gcp-bucket-settings.html
    - title: 将NetApp数据服务与Google云存储分段结合使用
      url: task-gcp-enable-data-services.html
  - title: 更多信息
    links:
    - title: 用于在BlueXP之外进行管理的Google Cloud Storage文档
      url: https://cloud.google.com/storage/docs/creating-buckets
  - title: 博客和社区
    links:
    - title: NetApp 社区
      url: https://community.netapp.com/t5/BlueXP-and-Services/ct-p/CDS
    - title: BlueXP博客
      url: https://bluexp.netapp.com/blog/topic/cloud-manager
    - title: 云网络研讨会
      url: https://bluexp.netapp.com/events
product-family:
  name: BlueXP
  repo: bluexp-family
